### ISSUE TITLE
IITK Email ID 

### ISSUE THREAD

**Issue by Deepak-Sangle** [ujwaljp/CS253_Project_MindHive#6]
I have signed up in your app and in the email id section i wrote 'deepak@iitk.ac.in' which is not even my iitk email id. Even then i got signed in. In this way, the app does not provide specificity to only iitk users and all people can access the website just by knowing the ending of the iitk email ids.

**Comment by harsh500** [comment]
but can you explain how will you get the link for register as it is not real id.

**Comment by Deepak-Sangle** [comment]
> 

I didn't quite get what you are asking. What I can say is that i had registered using a dummy iitk email id (which is "deepak@iitk.ac.in) and it still get registered and i can then sign in as well. So in this way there is no way you can verify that the user is from iitk or not.

**Comment by AdiPratapSingh** [comment]
The issue has been fixed. Kindly crosscheck it and feel free to reopen the issue in case of any discrepancy.
