### ISSUE TITLE
Questions asked by a user which is not anonymous

### ISSUE THREAD

**Issue by saicharan2570** [ujwaljp/CS253_Project_MindHive#7]
![Screenshot from 2022-04-17 19-15-42](https://user-images.githubusercontent.com/79274195/163717186-7eb7e034-9790-4d39-832a-7dec1f695774.png)
In this you have said that the other users anonymous questions can't be seen but even the question that is not anonymous isn't showing. I created a question from my account and i checked my profile from other account , when i tried to see the questions asked by me in other account ,it's showing no questions were asked.
![Screenshot from 2022-04-17 19-21-47](https://user-images.githubusercontent.com/79274195/163717387-3fc0016c-ef3c-4765-a523-b7173a209805.png)
this was the question created by me 
![Screenshot from 2022-04-17 19-23-14](https://user-images.githubusercontent.com/79274195/163717437-0c5a7b5b-6253-4851-9c62-b503673ab4fd.png)
It's showing no questions to display in other's account.

**Comment by harsh500** [comment]
Sorry for inconvenience but now this issue is resolved please check once confirm that it is working fine
thank you

**Comment by ashu8034** [comment]
No, we are still unable to see the questions.

**Comment by ris27hav** [comment]
Make sure you are up to date with this repo. Also, as we have not deployed this web app, make sure that both the users are working on the same device and making changes in the same local database. If the issue persists, please share steps to recreate this issue and screenshots.
